### ISSUE TITLE
question: how to get object of object?

### ISSUE THREAD

**Issue by mariusa** [nearprotocol/assemblyscript-json#339]
https://github.com/near/assemblyscript-json/blob/main/docs/classes/json.obj.md

How can one get object of object, since there's no `getObj` method on the actual object?

Example:
```
let ob = {
agenda {
  contact: {
    name: "John"
  }
}
}

ob.getObj('agenda') // works
ob.getObj('agenda').getObj('contact') // doesn't work

```

**Comment by JairusSW** [comment]
Use @serial-as/json. I think assemblyscript-json, which @serial-as/json depends on is unmaintained now
