### ISSUE TITLE
Implement JSON.parse in AssemblyScript

### ISSUE THREAD

**Issue by willemneal** [nearprotocol/assemblyscript-json#7]
Just wanted to share my [JSON handler](https://github.com/WebAssemblyOS/wasmos/blob/7a9f0f6d2b0d91691f55718c74626ea974f4166b/packages/assemblyscript/assembly/json/index.ts).  I can make a PR at a later date, but it's passing my initial tests so far.

For example you can do,
```ts
let obj = JSON.parse('{"hello": "world"}');
expect<string>(obj.getString("hello")).toStrictEqual("world");
```

**Comment by potatodepaulo** [comment]
@willemneal feel free to put in a PR when you are happy with your initial tests. This functionality would be great to have.

**Comment by lcoenen** [comment]
@willemneal why not using Maps and Sets to represent the whole thing?

**Comment by letmaik** [comment]
Isn't this done? https://github.com/nearprotocol/assemblyscript-json/pull/8

**Comment by willemneal** [comment]
@letmaik Yep!
